"""remove product imag_url

Revision ID: 060e2d1d959c
Revises: 09effa6c6e61
Create Date: 2025-04-24 10:23:49.408968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060e2d1d959c'
down_revision = '09effa6c6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
