"""add table productImage

Revision ID: 09effa6c6e61
Revises: e48ea5c395e9
Create Date: 2025-04-24 06:13:22.637277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09effa6c6e61'
down_revision = 'e48ea5c395e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('productImage_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('productImage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    # ### end Alembic commands ###
