"""add visitor table and gender for user

Revision ID: 30c0f5f79a25
Revises: 060e2d1d959c
Create Date: 2025-05-02 21:14:45.754123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c0f5f79a25'
down_revision = '060e2d1d959c'
branch_labels = None
depends_on = None

gender_enum = sa.Enum('male', 'female', 'other', name='genderenum')

def upgrade():
    # Membuat tipe enum di database
    gender_enum.create(op.get_bind())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
